name: Build and deploy to Dockerhub on commit

on:
    push:
        branches: 
            - master

jobs:
    Build-and-push-to-dockerhub:
        runs-on: ubuntu-latest
        steps:
           - name: checkout repo
             uses: actions/checkout@v2

           - name: Log in to dockerhub
             uses: docker/login-action@v1
             with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

           - name: Build and push docker image
             uses: docker/build-push-action@v2
             with: 
                context: .
                file: ./docker/Dockerfile.user
                push: true
                tags: nishta03/wallet-user-app:latest

           - name: Verify pushed image
             run: docker pull nishta03/wallet-user-app:latest

           - name: Deploy to EC2
             uses: appleboy/ssh-action@master
             with: 
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                key: ${{secrets.SSH_KEY}}
                script: |
                    sudo docker pull nishta03/wallet-user-app:latest
                    sudo docker stop web-app || true
                    sudo docker rm web-app || true
                    sudo docker run -d --name web-app -p 3005:3000 nishta03/wallet-user-app:latest



        

